version: '3.9'

services:
  digital:
    image: jv-digital
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Para persistir los uploads
      - ./public/uploads:/app/public/uploads

