version: '3.9'

services:
  digital:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env         # runtime — todas las variables
    ports:
      - "3000:3000"
    volumes:
      - ./public/uploads:/app/public/uploads
